export { Orb } from './orb'
export { ThinkingState, ThinkingSwap } from './thinking-state'
export { ThinkingIndicator } from './thinking-indicator'
export { AIAssistant } from './ai-assistant'
export type { OrbSize, OrbVariant, OrbTheme } from './orb'
export type { ThinkingStateProps } from './thinking-state'
export { useThinkingTask, useThinkingStore } from '@/lib/thinking'
export type { ThinkingTask, ThinkingVariant, ThinkingSize, ThinkingPriority } from '@/lib/thinking'
export { simulateAIThinking, mockAIResponse, getThinkingLabels, THINKING_LABELS } from '@/lib/ai-sim'
export type { ThinkingCategory } from '@/lib/ai-sim'
